// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load @"load-references.fsx"
#load @"..\AssemblyInfo.fs"
      @"..\Agent.fs"
      @"..\BlockingQueueAgent.fs"
      @"..\ByteOrder.fs"
      @"..\DnsSeed.fs"
      @"..\Messages.fs"
      @"..\MessageSerialization.fs"
      @"..\Socket.fs"
      @"..\SocketServer.fs"
      @"..\SocketClient.fs"
      @"..\Peer.fs"
      @"..\TestTemplate.fs"
      @"..\TestByteOrder.fs"
      @"..\TestBlockingQueueAgent.fs"
      @"..\TestDnsSeed.fs"
      @"..\TestMessageSerialization.fs"
      @"..\TestSocketClient.fs"
